import { useCallback, useEffect, useState } from 'react';
import type { api as defaultApi } from '@/services';
import { config } from '@/config';
import { t } from '@/i18n';

/**
 * Converts a URL-safe base64 VAPID public key (as generated by
 * `web-push generate-vapid-keys` and what the backend's VAPID_PUBLIC_KEY
 * holds) into the raw Uint8Array PushManager.subscribe() requires for
 * applicationServerKey -- the Push API doesn't accept a base64 string
 * directly.
 */
function urlBase64ToUint8Array(base64Url: string): Uint8Array<ArrayBuffer> {
  const padding = '='.repeat((4 - (base64Url.length % 4)) % 4);
  const base64 = (base64Url + padding).replace(/-/g, '+').replace(/_/g, '/');
  const raw = atob(base64);
  const bytes = new Uint8Array(new ArrayBuffer(raw.length));
  for (let i = 0; i < raw.length; i++) bytes[i] = raw.charCodeAt(i);
  return bytes;
}

export type PushSupport = 'unsupported' | 'supported';

type ToastFn = (m: string, action?: { label: string; fn: () => void }, kind?: 'success' | 'error') => void;

/**
 * Revokes this browser's Web Push registration: unsubscribes the local
 * PushSubscription (if one exists) and deletes the corresponding
 * push_subscriptions row on the backend. A no-op when the browser has no
 * active subscription, or doesn't support Push at all (config.vapidPublicKey
 * unset, or missing serviceWorker/PushManager -- in which case
 * navigator.serviceWorker is never touched).
 *
 * Shared by two callers with different error-handling needs, so this
 * function itself has none: it lets rejections propagate and leaves
 * catching/toasting to the caller.
 *  - `disablePush` below (explicit opt-out from Settings' NotificationsPanel)
 *    catches and shows an error toast.
 *  - `AppContext`'s `logout` (implicit revocation on every logout, so a
 *    shared/kiosk device doesn't keep delivering this account's push
 *    notifications to whoever uses the browser next -- push delivery is
 *    keyed server-side on team membership, not on holding a live session)
 *    fires-and-forgets it with `captureException`, matching how logout
 *    already treats its own `api.auth.logout()` failure as non-blocking.
 */
export async function unsubscribeWebPush(api: typeof defaultApi): Promise<void> {
  if (!config.vapidPublicKey || !('serviceWorker' in navigator) || !('PushManager' in window)) return;
  const reg = await navigator.serviceWorker.ready;
  const sub = await reg.pushManager.getSubscription();
  if (!sub) return;
  const endpoint = sub.endpoint;
  await sub.unsubscribe();
  await api.push.unsubscribe(endpoint);
}

/**
 * Drives the "enable Web Push" toggle in Settings' NotificationsPanel: reads the current
 * subscription state on mount, and exposes enable/disable actions that
 * register/unregister the browser's PushSubscription with the backend.
 * Deliberately not wired into AppContext's shared action object (unlike
 * most feature hooks) -- push opt-in is local, self-contained UI state with
 * no cross-sheet consumers, so threading it through the app-wide action list
 * would only add indirection.
 */
export function usePushActions(api: typeof defaultApi, toastMsg: ToastFn) {
  const support: PushSupport =
    config.vapidPublicKey && 'serviceWorker' in navigator && 'PushManager' in window ? 'supported' : 'unsupported';

  // null = not yet determined (initial check still in flight).
  const [subscribed, setSubscribed] = useState<boolean | null>(null);
  const [busy, setBusy] = useState(false);

  useEffect(() => {
    if (support === 'unsupported') {
      setSubscribed(false);
      return;
    }
    let cancelled = false;
    navigator.serviceWorker.ready
      .then((reg) => reg.pushManager.getSubscription())
      .then((sub) => {
        if (!cancelled) setSubscribed(!!sub);
      })
      .catch(() => {
        if (!cancelled) setSubscribed(false);
      });
    return () => {
      cancelled = true;
    };
  }, [support]);

  const enablePush = useCallback(async () => {
    if (support === 'unsupported' || busy) return;
    setBusy(true);
    try {
      const permission = await Notification.requestPermission();
      if (permission !== 'granted') {
        toastMsg(t('push.permissionDenied'), undefined, 'error');
        return;
      }
      const reg = await navigator.serviceWorker.ready;
      const sub =
        (await reg.pushManager.getSubscription()) ??
        (await reg.pushManager.subscribe({
          userVisibleOnly: true,
          applicationServerKey: urlBase64ToUint8Array(config.vapidPublicKey),
        }));
      await api.push.subscribe(sub.toJSON());
      setSubscribed(true);
      toastMsg(t('push.enabled'));
    } catch {
      toastMsg(t('push.enableFailed'), undefined, 'error');
    } finally {
      setBusy(false);
    }
  }, [api, busy, support, toastMsg]);

  const disablePush = useCallback(async () => {
    if (support === 'unsupported' || busy) return;
    setBusy(true);
    try {
      await unsubscribeWebPush(api);
      setSubscribed(false);
      toastMsg(t('push.disabled'));
    } catch {
      toastMsg(t('push.disableFailed'), undefined, 'error');
    } finally {
      setBusy(false);
    }
  }, [api, busy, support, toastMsg]);

  return { support, subscribed, busy, enablePush, disablePush };
}
