/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/providers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List available login providers */
        get: operations["listProviders"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Authenticate with email + password */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Invalidate current session */
        post: operations["logout"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get authenticated user profile */
        get: operations["getCurrentUser"];
        put?: never;
        post?: never;
        /**
         * Erase the authenticated account (GDPR Art. 17, by anonymization)
         * @description Anonymizes the user's personal data (name, email, phone, birthday, address, photo) and strips free-text PII from their comments and absence reasons, then deletes all of their sessions. Membership, attendance and finance records are retained in anonymized form so that shared and legally required data (e.g. accounting) stays intact. The request is authorized by the active session; to confirm intent the caller must echo the account's own email address (works regardless of login method, including OIDC accounts that have no password).
         */
        delete: operations["deleteCurrentUser"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/data-export": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Export the authenticated user's personal data (GDPR Art. 15)
         * @description Returns a single JSON document with all personal data held about the authenticated user: profile, memberships and roles, attendance, comments, absences, authored news, created polls, votes, penalty assignments and contributions.
         */
        get: operations["getMyDataExport"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/me/photo": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get user profile photo */
        get: operations["getMyPhoto"];
        /** Upload / replace profile photo (scaled to max 800×800 px) */
        put: operations["uploadMyPhoto"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** List teams the authenticated user belongs to */
        get: operations["listTeams"];
        put?: never;
        /** Create a new team */
        post: operations["createTeam"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** Get a single team */
        get: operations["getTeam"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update team settings */
        patch: operations["updateTeam"];
        trace?: never;
    };
    "/teams/{teamId}/photo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** Get team photo */
        get: operations["getTeamPhoto"];
        /** Upload team photo (scaled to max 800×800 px) */
        put: operations["uploadTeamPhoto"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/logo": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** Get team logo */
        get: operations["getTeamLogo"];
        /** Upload team logo (scaled to max 800×800 px) */
        put: operations["uploadTeamLogo"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/invite": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Generate a 7-day invite link */
        post: operations["createInvite"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/members": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** List team members */
        get: operations["listMembers"];
        put?: never;
        /** Add a member to the team */
        post: operations["addMember"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/members/{membershipId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                membershipId: components["parameters"]["membershipId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove member from team */
        delete: operations["removeMember"];
        options?: never;
        head?: never;
        /** Update member profile */
        patch: operations["updateMember"];
        trace?: never;
    };
    "/teams/{teamId}/members/{membershipId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                membershipId: components["parameters"]["membershipId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Replace member role assignments */
        put: operations["setMemberRoles"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/roles": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** List team roles */
        get: operations["listRoles"];
        put?: never;
        /** Create a custom role */
        post: operations["createRole"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/roles/{roleId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                roleId: components["parameters"]["roleId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete role */
        delete: operations["deleteRole"];
        options?: never;
        head?: never;
        /** Update role */
        patch: operations["updateRole"];
        trace?: never;
    };
    "/teams/{teamId}/events": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** List events */
        get: operations["listEvents"];
        put?: never;
        /** Create event (recurring → creates series + instances) */
        post: operations["createEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/events/{eventId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        /** Get single event with attendance summary */
        get: operations["getEvent"];
        put?: never;
        post?: never;
        /** Delete event */
        delete: operations["deleteEvent"];
        options?: never;
        head?: never;
        /** Update event */
        patch: operations["updateEvent"];
        trace?: never;
    };
    "/teams/{teamId}/events/{eventId}/status": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Activate or cancel event */
        post: operations["setEventStatus"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/events/{eventId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        /** List comments for event */
        get: operations["listEventComments"];
        put?: never;
        /** Add comment to event */
        post: operations["addEventComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/events/{eventId}/comments/{commentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
                commentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete comment */
        delete: operations["deleteEventComment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/events/{eventId}/attendance": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        /** Get attendance matrix for event */
        get: operations["listAttendance"];
        put?: never;
        /** Set attendance status for a user */
        post: operations["setAttendance"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/events/{eventId}/attendance/nominations": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        get?: never;
        /** Nominate or denominate a member for event */
        put: operations["setNomination"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/absences": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** List absences for the team */
        get: operations["listAbsences"];
        put?: never;
        /** Create absence entry */
        post: operations["createAbsence"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/absences/mine": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** List authenticated user's own absences */
        get: operations["listMyAbsences"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/absences/{absenceId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                absenceId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete absence */
        delete: operations["deleteAbsence"];
        options?: never;
        head?: never;
        /** Update absence */
        patch: operations["updateAbsence"];
        trace?: never;
    };
    "/teams/{teamId}/news": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** List team news */
        get: operations["listNews"];
        put?: never;
        /** Create news item */
        post: operations["createNews"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/news/{newsId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                newsId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete news item */
        delete: operations["deleteNews"];
        options?: never;
        head?: never;
        /** Update news item */
        patch: operations["updateNews"];
        trace?: never;
    };
    "/teams/{teamId}/polls": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** List polls with vote counts */
        get: operations["listPolls"];
        put?: never;
        /** Create poll */
        post: operations["createPoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/polls/{pollId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                pollId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete poll */
        delete: operations["deletePoll"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/polls/{pollId}/vote": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                pollId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Cast vote on poll */
        post: operations["votePoll"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/notifications": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** List team notifications (last 62 days) */
        get: operations["listNotifications"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/notifications/seen": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Mark all notifications as seen */
        post: operations["markNotificationsSeen"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/finances": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** Get full financial overview */
        get: operations["getFinanceOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/finances/transactions": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Add income or expense */
        post: operations["createTransaction"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/finances/transactions/{transactionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                transactionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete transaction */
        delete: operations["deleteTransaction"];
        options?: never;
        head?: never;
        /** Update transaction */
        patch: operations["updateTransaction"];
        trace?: never;
    };
    "/teams/{teamId}/finances/penalties": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Create penalty template */
        post: operations["createPenalty"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/finances/penalties/{penaltyId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                penaltyId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Delete penalty template and all assignments */
        delete: operations["deletePenalty"];
        options?: never;
        head?: never;
        /** Update penalty template */
        patch: operations["updatePenalty"];
        trace?: never;
    };
    "/teams/{teamId}/finances/penalty-assignments": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Assign penalty to member */
        post: operations["createPenaltyAssignment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/finances/penalty-assignments/{assignmentId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                assignmentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        /** Remove penalty assignment */
        delete: operations["deletePenaltyAssignment"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/finances/penalty-assignments/{assignmentId}/toggle-paid": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                assignmentId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle paid status of penalty assignment */
        post: operations["togglePenaltyPaid"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/finances/contributions/{contributionId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                contributionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        /** Update contribution amount or label */
        patch: operations["updateContribution"];
        trace?: never;
    };
    "/teams/{teamId}/finances/contributions/{contributionId}/toggle": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                contributionId: string;
            };
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Toggle contribution paid/open */
        post: operations["toggleContribution"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/stats": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        /** Team attendance statistics */
        get: operations["getStatsOverview"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/teams/{teamId}/stats/members/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                userId: string;
            };
            cookie?: never;
        };
        /** Individual member attendance statistics */
        get: operations["getMemberStats"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description RFC 9457 Problem Details */
        Problem: {
            type?: string;
            title?: string;
            status?: number;
            detail?: string;
        };
        /** @enum {string} */
        PermLevel: "none" | "read" | "write";
        /** @description Per-module permission levels */
        Permissions: {
            events: components["schemas"]["PermLevel"];
            members: components["schemas"]["PermLevel"];
            finances: components["schemas"]["PermLevel"];
            news: components["schemas"]["PermLevel"];
            polls: components["schemas"]["PermLevel"];
            settings: components["schemas"]["PermLevel"];
        };
        /** @enum {string} */
        EventType: "training" | "auftritt" | "event";
        /** @enum {string} */
        EventStatus: "active" | "cancelled";
        /** @enum {string} */
        AttendanceStatus: "yes" | "no" | "maybe" | "pending" | "not_nominated";
        /** @enum {string} */
        ResponseMode: "opt_in" | "opt_out";
        /** @enum {string} */
        TransactionType: "income" | "expense";
        /** @enum {string} */
        ContributionStatus: "paid" | "open";
        /** @enum {string} */
        NotificationType: "attendance" | "event_created" | "event_updated" | "event_cancelled" | "event_reactivated" | "event_deleted" | "news" | "poll" | "absence";
        Provider: {
            id: string;
            name: string;
            sub: string;
            glyph: string;
            bg: string;
            fg: string;
            border?: string;
        };
        LoginRequest: {
            /** Format: email */
            email: string;
            password: string;
        };
        LoginResponse: {
            token: string;
            user: components["schemas"]["User"];
        };
        DeleteAccountRequest: {
            /**
             * Format: email
             * @description The account's own email address, retyped to confirm the irreversible erasure. Must match the authenticated user's email.
             */
            confirmEmail: string;
        };
        User: {
            /** Format: uuid */
            id: string;
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            avatarColor: string;
            /** Format: date */
            birthday?: string;
            address?: string;
            hasPhoto?: boolean;
        };
        Team: {
            /** Format: uuid */
            id: string;
            name: string;
            short?: string;
            icon?: string;
            iconBg?: string;
            iconFg?: string;
            description?: string;
            hasPhoto?: boolean;
            hasLogo?: boolean;
            reasonVisibilityRoleIds?: string[];
        };
        TeamForUser: components["schemas"]["Team"] & {
            myRoles: components["schemas"]["Role"][];
            myPerms: components["schemas"]["Permissions"];
            /** Format: uuid */
            membershipId: string;
            memberCount: number;
        };
        CreateTeamRequest: {
            name: string;
            icon?: string;
            iconBg?: string;
            iconFg?: string;
        };
        UpdateTeamRequest: {
            name?: string;
            short?: string;
            icon?: string;
            iconBg?: string;
            iconFg?: string;
            description?: string;
            reasonVisibilityRoleIds?: string[];
        };
        Invite: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teamId: string;
            code: string;
            link: string;
            /** Format: date-time */
            createdAt: string;
            /** Format: date-time */
            expiresAt: string;
        };
        Role: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teamId: string;
            name: string;
            system: boolean;
            color?: string;
            permissions: components["schemas"]["Permissions"];
        };
        CreateRoleRequest: {
            name: string;
            color?: string;
            permissions: components["schemas"]["Permissions"];
        };
        UpdateRoleRequest: {
            name?: string;
            color?: string;
            permissions?: components["schemas"]["Permissions"];
        };
        Member: {
            /** Format: uuid */
            membershipId: string;
            /** Format: uuid */
            userId: string;
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            /** Format: date */
            birthday?: string;
            address?: string;
            avatarColor: string;
            hasPhoto?: boolean;
            group?: string;
            roles: components["schemas"]["Role"][];
            primaryRole?: components["schemas"]["Role"];
            perms?: components["schemas"]["Permissions"];
            /** Format: date-time */
            joinedAt: string;
        };
        AddMemberRequest: {
            name: string;
            /** Format: email */
            email: string;
            phone?: string;
            roleIds?: string[];
            group?: string;
        };
        UpdateMemberRequest: {
            name?: string;
            /** Format: email */
            email?: string;
            phone?: string;
            /** Format: date */
            birthday?: string;
            address?: string;
            roleIds?: string[];
            group?: string;
        };
        SetRolesRequest: {
            roleIds: string[];
        };
        EventSummary: {
            yes: number;
            no: number;
            maybe: number;
            pending: number;
            notNominated: number;
            nominated: number;
            total: number;
        };
        TeamEvent: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teamId: string;
            /** Format: uuid */
            seriesId?: string;
            type: components["schemas"]["EventType"];
            title: string;
            /** Format: date */
            date: string;
            location?: string;
            note?: string;
            result?: string;
            /** @description HH:mm */
            meetTime?: string;
            /** @description HH:mm */
            startTime?: string;
            /** @description HH:mm */
            endTime?: string;
            meetTimeMandatory?: boolean;
            responseMode?: components["schemas"]["ResponseMode"];
            nominatedRoleIds?: string[];
            recurring: boolean;
            status: components["schemas"]["EventStatus"];
            summary: components["schemas"]["EventSummary"];
            myStatus?: components["schemas"]["AttendanceStatus"];
            myAuto?: boolean;
            myReason?: string;
        };
        CreateEventRequest: {
            type: components["schemas"]["EventType"];
            title: string;
            /** Format: date */
            date: string;
            location?: string;
            note?: string;
            meetTime?: string;
            startTime?: string;
            endTime?: string;
            meetTimeMandatory?: boolean;
            responseMode?: components["schemas"]["ResponseMode"];
            nominatedRoleIds?: string[];
            recurring?: boolean;
            repeatWeeks?: number;
        };
        UpdateEventRequest: {
            type?: components["schemas"]["EventType"];
            title?: string;
            /** Format: date */
            date?: string;
            location?: string;
            note?: string;
            meetTime?: string;
            startTime?: string;
            endTime?: string;
            meetTimeMandatory?: boolean;
            responseMode?: components["schemas"]["ResponseMode"];
            nominatedRoleIds?: string[];
        };
        SetEventStatusRequest: {
            status: components["schemas"]["EventStatus"];
        };
        EventComment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            eventId: string;
            /** Format: uuid */
            userId: string;
            text: string;
            /** Format: date-time */
            createdAt: string;
            authorName?: string;
            authorColor?: string;
            hasAuthorPhoto?: boolean;
        };
        AddCommentRequest: {
            text: string;
        };
        AttendanceRecord: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            eventId: string;
            /** Format: uuid */
            userId: string;
            status: components["schemas"]["AttendanceStatus"];
            reason?: string;
            reasonId?: string;
            /** @enum {string} */
            reasonVisibility?: "trainers" | "team";
            /** Format: date-time */
            at?: string;
        };
        AttendanceRow: {
            /** Format: uuid */
            userId: string;
            name: string;
            avatarColor: string;
            hasPhoto?: boolean;
            group?: string;
            primaryRole?: components["schemas"]["Role"];
            status: components["schemas"]["AttendanceStatus"];
            reason?: string;
            reasonId?: string;
            /** @enum {string} */
            reasonVisibility?: "trainers" | "team";
            auto?: boolean;
            absent?: boolean;
        };
        SetAttendanceRequest: {
            /** Format: uuid */
            userId: string;
            status: components["schemas"]["AttendanceStatus"];
            reason?: string;
            reasonId?: string;
            /** @enum {string} */
            reasonVisibility?: "trainers" | "team";
        };
        SetNominationRequest: {
            /** Format: uuid */
            userId: string;
            nominated: boolean;
        };
        Absence: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            userId: string;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            reason?: string;
            /** Format: date-time */
            createdAt: string;
            memberName?: string;
            memberAvatarColor?: string;
            hasPhoto?: boolean;
            roleColor?: string;
            roleName?: string;
        };
        CreateAbsenceRequest: {
            /** Format: uuid */
            userId: string;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
            reason?: string;
        };
        UpdateAbsenceRequest: {
            /** Format: date */
            from?: string;
            /** Format: date */
            to?: string;
            reason?: string;
        };
        NewsItem: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teamId: string;
            /** Format: uuid */
            authorId: string;
            title: string;
            body: string;
            pinned: boolean;
            /** Format: date-time */
            createdAt: string;
            authorName?: string;
            authorColor?: string;
            hasAuthorPhoto?: boolean;
        };
        CreateNewsRequest: {
            title: string;
            body: string;
            /** @default false */
            pinned: boolean;
        };
        UpdateNewsRequest: {
            title?: string;
            body?: string;
            pinned?: boolean;
        };
        PollOption: {
            /** Format: uuid */
            id: string;
            text: string;
            count: number;
            /** Format: float */
            pct: number;
            voters?: {
                name?: string;
                color?: string;
                hasPhoto?: boolean;
            }[];
        };
        Poll: {
            /** Format: uuid */
            id: string;
            question: string;
            multiple: boolean;
            anonymous: boolean;
            /** Format: date-time */
            createdAt: string;
            totalVotes: number;
            myVote?: string[];
            options: components["schemas"]["PollOption"][];
        };
        CreatePollRequest: {
            question: string;
            options: string[];
            /** @default false */
            multiple: boolean;
            /** @default false */
            anonymous: boolean;
        };
        VotePollRequest: {
            optionIds: string[];
        };
        AppNotification: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teamId: string;
            type: components["schemas"]["NotificationType"];
            /** Format: uuid */
            actorId?: string;
            status?: components["schemas"]["AttendanceStatus"];
            title?: string;
            /** Format: uuid */
            eventId?: string;
            eventTitle?: string;
            /** Format: date */
            eventDate?: string;
            note?: string;
            /** Format: date-time */
            createdAt: string;
            actorName?: string;
            actorColor?: string;
            hasActorPhoto?: boolean;
            unread?: boolean;
        };
        NotificationsResult: {
            items: components["schemas"]["AppNotification"][];
            unreadCount: number;
        };
        Transaction: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teamId: string;
            type: components["schemas"]["TransactionType"];
            title: string;
            /** Format: double */
            amount: number;
            /** Format: date */
            date: string;
            category?: string;
        };
        CreateTransactionRequest: {
            type: components["schemas"]["TransactionType"];
            title: string;
            /** Format: double */
            amount: number;
            category?: string;
        };
        UpdateTransactionRequest: {
            type?: components["schemas"]["TransactionType"];
            title?: string;
            /** Format: double */
            amount?: number;
            category?: string;
        };
        Penalty: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teamId: string;
            label: string;
            /** Format: double */
            amount: number;
        };
        CreatePenaltyRequest: {
            label: string;
            /** Format: double */
            amount: number;
        };
        UpdatePenaltyRequest: {
            label?: string;
            /** Format: double */
            amount?: number;
        };
        PenaltyAssignment: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teamId: string;
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            penaltyId: string;
            paid: boolean;
            /** Format: date */
            date: string;
            memberName?: string;
            memberAvatarColor?: string;
            hasPhoto?: boolean;
            label?: string;
            /** Format: double */
            amount?: number;
        };
        CreatePenaltyAssignmentRequest: {
            /** Format: uuid */
            userId: string;
            /** Format: uuid */
            penaltyId: string;
        };
        OpenPenalty: {
            /** Format: uuid */
            userId: string;
            name: string;
            avatarColor: string;
            hasPhoto?: boolean;
            /** Format: double */
            amount: number;
        };
        Contribution: {
            /** Format: uuid */
            id: string;
            /** Format: uuid */
            teamId: string;
            /** Format: uuid */
            userId: string;
            /** @description YYYY-MM */
            month: string;
            label?: string;
            /** Format: double */
            amount: number;
            status: components["schemas"]["ContributionStatus"];
            memberName?: string;
            memberAvatarColor?: string;
            hasPhoto?: boolean;
        };
        UpdateContributionRequest: {
            label?: string;
            /** Format: double */
            amount?: number;
        };
        FinanceOverview: {
            /** Format: double */
            balance: number;
            /** Format: double */
            income: number;
            /** Format: double */
            expense: number;
            transactions: components["schemas"]["Transaction"][];
            penalties: components["schemas"]["Penalty"][];
            assignments: components["schemas"]["PenaltyAssignment"][];
            openPenalties: components["schemas"]["OpenPenalty"][];
            /** Format: double */
            openPenaltySum: number;
            contributions: components["schemas"]["Contribution"][];
            contribOpen: number;
        };
        MemberAttendanceStats: {
            /** Format: float */
            quote: number;
            counted: number;
            yes: number;
        };
        MemberStat: {
            /** Format: uuid */
            userId: string;
            name: string;
            avatarColor: string;
            hasPhoto?: boolean;
            /** Format: float */
            quote: number;
            counted: number;
            yes: number;
        };
        EventStat: {
            /** Format: uuid */
            id: string;
            title: string;
            type: components["schemas"]["EventType"];
            /** Format: date */
            date: string;
            yes: number;
            nominated: number;
            /** Format: float */
            pct: number;
            enough: boolean;
        };
        StatsOverview: {
            /** Format: float */
            avg: number;
            members: components["schemas"]["MemberStat"][];
            events: components["schemas"]["EventStat"][];
            pastCount: number;
            /** Format: date */
            from: string;
            /** Format: date */
            to: string;
        };
    };
    responses: {
        /** @description Unauthorized */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Not Found */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
        /** @description Forbidden */
        Forbidden: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/problem+json": components["schemas"]["Problem"];
            };
        };
    };
    parameters: {
        teamId: string;
        membershipId: string;
        eventId: string;
        roleId: string;
        limit: number;
        offset: number;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    listProviders: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Provider"][];
                };
            };
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    logout: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    deleteCurrentUser: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DeleteAccountRequest"];
            };
        };
        responses: {
            /** @description Account anonymized; session cleared */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyDataExport: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Personal-data export document. */
            200: {
                headers: {
                    /** @description Suggests a download filename. */
                    "Content-Disposition"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: unknown;
                    };
                };
            };
            401: components["responses"]["Unauthorized"];
        };
    };
    getMyPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadMyPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    photo: string;
                };
            };
        };
        responses: {
            /** @description Updated user */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
        };
    };
    listTeams: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamForUser"][];
                };
            };
        };
    };
    createTeam: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTeamRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamForUser"];
                };
            };
        };
    };
    getTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    updateTeam: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTeamRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
        };
    };
    getTeamPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadTeamPhoto: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    photo: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
        };
    };
    getTeamLogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description JPEG image */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "image/jpeg": string;
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    uploadTeamLogo: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "multipart/form-data": {
                    /** Format: binary */
                    logo: string;
                };
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Team"];
                };
            };
        };
    };
    createInvite: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Invite"];
                };
            };
        };
    };
    listMembers: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"][];
                };
            };
        };
    };
    addMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddMemberRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    removeMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                membershipId: components["parameters"]["membershipId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateMember: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                membershipId: components["parameters"]["membershipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateMemberRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    setMemberRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                membershipId: components["parameters"]["membershipId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetRolesRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Member"];
                };
            };
        };
    };
    listRoles: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"][];
                };
            };
        };
    };
    createRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateRoleRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    deleteRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                roleId: components["parameters"]["roleId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateRole: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                roleId: components["parameters"]["roleId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateRoleRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Role"];
                };
            };
        };
    };
    listEvents: {
        parameters: {
            query?: {
                scope?: "upcoming" | "past" | "all";
                limit?: components["parameters"]["limit"];
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamEvent"][];
                };
            };
        };
    };
    createEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateEventRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamEvent"];
                };
            };
        };
    };
    getEvent: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamEvent"];
                };
            };
            404: components["responses"]["NotFound"];
        };
    };
    deleteEvent: {
        parameters: {
            query?: {
                scope?: "single" | "series";
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateEvent: {
        parameters: {
            query?: {
                scope?: "single" | "series";
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateEventRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamEvent"];
                };
            };
        };
    };
    setEventStatus: {
        parameters: {
            query?: {
                scope?: "single" | "series";
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetEventStatusRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TeamEvent"];
                };
            };
        };
    };
    listEventComments: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventComment"][];
                };
            };
        };
    };
    addEventComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["AddCommentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EventComment"];
                };
            };
        };
    };
    deleteEventComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
                commentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRow"][];
                };
            };
        };
    };
    setAttendance: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetAttendanceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AttendanceRecord"];
                };
            };
        };
    };
    setNomination: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                eventId: components["parameters"]["eventId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SetNominationRequest"];
            };
        };
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    listAbsences: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Absence"][];
                };
            };
        };
    };
    createAbsence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateAbsenceRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Absence"];
                };
            };
        };
    };
    listMyAbsences: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Absence"][];
                };
            };
        };
    };
    deleteAbsence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                absenceId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateAbsence: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                absenceId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateAbsenceRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Absence"];
                };
            };
        };
    };
    listNews: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItem"][];
                };
            };
        };
    };
    createNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateNewsRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItem"];
                };
            };
        };
    };
    deleteNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                newsId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateNews: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                newsId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateNewsRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NewsItem"];
                };
            };
        };
    };
    listPolls: {
        parameters: {
            query?: {
                limit?: components["parameters"]["limit"];
                offset?: components["parameters"]["offset"];
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Poll"][];
                };
            };
        };
    };
    createPoll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePollRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Poll"];
                };
            };
        };
    };
    deletePoll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                pollId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    votePoll: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                pollId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["VotePollRequest"];
            };
        };
        responses: {
            /** @description Updated poll */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Poll"];
                };
            };
        };
    };
    listNotifications: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["NotificationsResult"];
                };
            };
        };
    };
    markNotificationsSeen: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    getFinanceOverview: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["FinanceOverview"];
                };
            };
        };
    };
    createTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreateTransactionRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    deleteTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updateTransaction: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                transactionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateTransactionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Transaction"];
                };
            };
        };
    };
    createPenalty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePenaltyRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Penalty"];
                };
            };
        };
    };
    deletePenalty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                penaltyId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    updatePenalty: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                penaltyId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePenaltyRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Penalty"];
                };
            };
        };
    };
    createPenaltyAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["CreatePenaltyAssignmentRequest"];
            };
        };
        responses: {
            /** @description Created */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenaltyAssignment"];
                };
            };
        };
    };
    deletePenaltyAssignment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description No Content */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
        };
    };
    togglePenaltyPaid: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                assignmentId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PenaltyAssignment"];
                };
            };
        };
    };
    updateContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                contributionId: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdateContributionRequest"];
            };
        };
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
        };
    };
    toggleContribution: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                contributionId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Contribution"];
                };
            };
        };
    };
    getStatsOverview: {
        parameters: {
            query?: {
                from?: string;
                to?: string;
            };
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StatsOverview"];
                };
            };
        };
    };
    getMemberStats: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                teamId: components["parameters"]["teamId"];
                userId: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description OK */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["MemberAttendanceStats"];
                };
            };
        };
    };
}
