{{- if .Values.cookieEncryption.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-cookie-encryption
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.cookieEncryption.secret.existingSecretKeys.key }}: {{ .Values.cookieEncryption.secret.key | b64enc }}
  {{ .Values.cookieEncryption.secret.existingSecretKeys.keys }}: {{ .Values.cookieEncryption.secret.keys | b64enc }}
{{- end }}
