{{- if .Values.jwt.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-jwt
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  JWT_PRIVATE_KEY: {{ .Values.jwt.secret.privateKey | b64enc }}
  JWT_PUBLIC_KEY: {{ .Values.jwt.secret.publicKey | b64enc }}
{{- end }}
