{{- if .Values.metrics.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-metrics
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.metrics.secret.existingSecretKey }}: {{ .Values.metrics.secret.token | b64enc }}
{{- end }}
