{{- if and .Values.monitoring.enabled .Values.monitoring.metricsToken }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-metrics-token
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  token: {{ .Values.monitoring.metricsToken | b64enc }}
{{- end }}
