{{- if .Values.pagination.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-pagination
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  PAGINATION_HMAC_KEY: {{ .Values.pagination.secret.hmacKey | b64enc }}
{{- end }}
