{{- if .Values.push.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-push
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  VAPID_PRIVATE_KEY: {{ .Values.push.secret.privateKey | b64enc }}
{{- end }}
