{{- if .Values.s3.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-s3
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.s3.secret.existingSecretKeys.accessKeyId }}: {{ .Values.s3.secret.accessKeyId | b64enc }}
  {{ .Values.s3.secret.existingSecretKeys.secretAccessKey }}: {{ .Values.s3.secret.secretAccessKey | b64enc }}
{{- end }}
