{{- if .Values.s3.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-s3
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  S3_ACCESS_KEY_ID: {{ .Values.s3.secret.accessKeyId | b64enc }}
  S3_SECRET_ACCESS_KEY: {{ .Values.s3.secret.secretAccessKey | b64enc }}
{{- end }}
