{{- if .Values.observability.sentry.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-sentry
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  SENTRY_DSN: {{ .Values.observability.sentry.secret.dsn | b64enc }}
{{- end }}
