{{- if .Values.smtp.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-smtp
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  SMTP_USERNAME: {{ .Values.smtp.secret.username | b64enc }}
  SMTP_PASSWORD: {{ .Values.smtp.secret.password | b64enc }}
{{- end }}
