{{- if .Values.smtp.secret.create }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "team-manager.fullname" . }}-smtp
  labels:
    {{- include "team-manager.labels" . | nindent 4 }}
type: Opaque
data:
  {{ .Values.smtp.secret.existingSecretKeys.username }}: {{ .Values.smtp.secret.username | b64enc }}
  {{ .Values.smtp.secret.existingSecretKeys.password }}: {{ .Values.smtp.secret.password | b64enc }}
{{- end }}
