package main

import (
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"
	"gopkg.in/yaml.v3"
)

func parseDoc(t *testing.T, spec string) *yaml.Node {
	t.Helper()
	var doc yaml.Node
	require.NoError(t, yaml.Unmarshal([]byte(spec), &doc))
	return &doc
}

const validSpec = `
paths:
  /teams:
    get:
      operationId: listTeams
  /teams/{teamId}:
    get:
      operationId: getTeam
      x-rbac-module: public
    patch:
      operationId: updateTeam
      x-rbac-module: settings
  /teams/{teamId}/events/{eventId}/attendance:
    post:
      operationId: setAttendance
      x-rbac-module: events
      x-rbac-self-service: true
`

func TestExtractRoutes_SkipsNonTeamScopedOperations(t *testing.T) {
	entries, err := extractRoutes(parseDoc(t, validSpec))
	require.NoError(t, err)

	for _, e := range entries {
		assert.NotEqual(t, "listTeams", e.OperationID, "non-team-scoped operations must not appear in the table")
	}
	assert.Len(t, entries, 3)
}

func TestExtractRoutes_ReadsModuleAndSelfService(t *testing.T) {
	entries, err := extractRoutes(parseDoc(t, validSpec))
	require.NoError(t, err)

	byOpID := make(map[string]routeEntry)
	for _, e := range entries {
		byOpID[e.OperationID] = e
	}

	got := byOpID["getTeam"]
	assert.Equal(t, "GET", got.Method)
	assert.Nil(t, got.Segments)
	assert.Equal(t, "public", got.Module)
	assert.False(t, got.SelfService)

	got = byOpID["updateTeam"]
	assert.Equal(t, "settings", got.Module)
	assert.False(t, got.SelfService)

	got = byOpID["setAttendance"]
	assert.Equal(t, "POST", got.Method)
	assert.Equal(t, []string{"events", "{eventId}", "attendance"}, got.Segments)
	assert.Equal(t, "events", got.Module)
	assert.True(t, got.SelfService)
}

func TestExtractRoutes_MissingModule_Errors(t *testing.T) {
	spec := `
paths:
  /teams/{teamId}/widgets:
    get:
      operationId: listWidgets
`
	_, err := extractRoutes(parseDoc(t, spec))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "listWidgets")
	assert.Contains(t, err.Error(), "missing x-rbac-module")
}

func TestExtractRoutes_UnknownModule_Errors(t *testing.T) {
	spec := `
paths:
  /teams/{teamId}/widgets:
    get:
      operationId: listWidgets
      x-rbac-module: nonsense
`
	_, err := extractRoutes(parseDoc(t, spec))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "not a recognized module")
}

func TestExtractRoutes_MissingOperationID_Errors(t *testing.T) {
	spec := `
paths:
  /teams/{teamId}/widgets:
    get:
      x-rbac-module: public
`
	_, err := extractRoutes(parseDoc(t, spec))
	require.Error(t, err)
	assert.Contains(t, err.Error(), "no operationId")
}

func TestPathSegmentsAfterTeam(t *testing.T) {
	cases := map[string][]string{
		"/teams/{teamId}":                             nil,
		"/teams/{teamId}/photo":                       {"photo"},
		"/teams/{teamId}/events/{eventId}/attendance": {"events", "{eventId}", "attendance"},
	}
	for path, want := range cases {
		assert.Equal(t, want, pathSegmentsAfterTeam(path), path)
	}
}

func TestSegmentsLiteral(t *testing.T) {
	assert.Equal(t, "nil", segmentsLiteral(nil))
	assert.Equal(t, `[]string{"events", "{eventId}"}`, segmentsLiteral([]string{"events", "{eventId}"}))
}

func TestRenderTable_ProducesValidGoSource(t *testing.T) {
	entries, err := extractRoutes(parseDoc(t, validSpec))
	require.NoError(t, err)

	out, err := renderTable(entries)
	require.NoError(t, err)
	assert.True(t, strings.HasPrefix(string(out), "// Code generated by cmd/genrbac"))
	assert.Contains(t, string(out), "package middleware")
}
