import type { SidebarsConfig } from '@docusaurus/plugin-content-docs';

// Manually ordered (not autogenerated) so the sidebar follows a sensible
// reading order instead of alphabetical filename order.
const sidebars: SidebarsConfig = {
  endUserSidebar: [
    {
      type: 'doc',
      id: 'README',
      label: 'Übersicht',
    },
    {
      type: 'category',
      label: 'Einstieg',
      collapsed: false,
      items: ['erste-schritte', 'rollen-und-rechte'],
    },
    {
      type: 'category',
      label: 'Funktionen',
      collapsed: false,
      items: [
        'termine',
        'mitglieder',
        'finanzen',
        'news',
        'umfragen',
        'team-einstellungen',
        'statistik',
      ],
    },
    {
      type: 'category',
      label: 'Konto & Datenschutz',
      collapsed: false,
      items: ['daten-und-datenschutz'],
    },
  ],
};

export default sidebars;
